[package]
name = "rust-quadtree-art"
version = "0.2.0"
edition = "2021"
description = "Generate quadtree art from images"
license = "MIT"

[dependencies]
image = "0.25"
imageproc = "0.24"
clap = { version = "4.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3.0"
